name: pa_int_template_dbt

version: 1.0.0

config-version: 2

profile: pa_int_template_dbt

model-paths:
  - models

snapshot-paths:
  - snapshots

test-paths:
  - tests

macro-paths:
  - macros

seed-paths:
  - seeds

models:

  pa_int_template_dbt:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table

snapshots:
  +target_schema: snapshots
