name: dbt-deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt

      - run: dbt deps

      - run: dbt build --target prod
